In [5]:
import numpy as np

In [6]:
def mean(l):
    return sum(l)/len(l)

def calculate_thetas(E,gam, n):
    """return list of thetas"""
    results = []
    for i, e_i in enumerate(E):
        copy = E.copy()
        E_others = np.delete(copy, i)
        
        theta = sum([e_j - (1/(n-1)) * sum(E_others) for e_j in E_others])
        
        theta *= (gam/2)*(1/(n-2))
        
        results.append(theta)
    return results

def cost_fun(N, gam, e, qq, mechanism="OGL"):
    e = np.array(e)
    n = len(e)
    cost_baseshare = qq/N*sum(e)
    cost_theta = np.array([])
        
    if mechanism == 'MPT':
        cost = cost_baseshare
    elif mechanism == 'MGL':        
        cost_varpenalty = gam/2*(n/(n-1))*(e-mean(e))**2
        cost = cost_baseshare + cost_varpenalty
    elif mechanism == 'OGL':
        cost_varpenalty = gam/2*(n/(n-1))*(e-mean(e))*2
                
        cost_theta = np.array(calculate_thetas(e, gam, n))
        
        print(f"{cost_theta}") 
    
    cost = cost_baseshare + cost_varpenalty - cost_theta
    
    return cost        

In [7]:
qq = 1000
gam = 15
n = N = 4
e = [10,0,0,0]

participant_costs = cost_fun(N, gam, e, qq, mechanism="OGL")
print(participant_costs)

Cost_baseshare: 2500.0
cost_varpenalty: [150. -50. -50. -50.]
[0 0 0]
[10  0  0]
[10  0  0]
[10  0  0]
[0.00000000e+00 3.33066907e-15 3.33066907e-15 3.33066907e-15]
[2650. 2450. 2450. 2450.]
